name: aws-ecr-docker-image-pylint-pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Not specifying ECR Repository or image tag as we only have one
    - name: Docker pull and run from Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_REGISTRY_URL }}
      run: |
        docker pull $ECR_REGISTRY
        docker run $ECR_REGISTRY
        ls -al
    - name: Run pylint
      run: |
        pipenv run pylint --rcfile=pylint.cfg $(git ls-files '*.py') -s true --fail-under=10

    - name: Run pytest
      run: |
        pipenv run pytest
