name: pylint-pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache pipenv
      uses: actions/cache@v2
      id: cache-pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Run PyLint
      run: |
        pipenv run pylint --rcfile=pylint.cfg $(git ls-files '*.py') -s true --fail-under=10

    - name: Generate csv files
      run: |
        pipenv run python generate_data/generate_csv_data.py -g 10 -type flights bus train -v -o

    - name: Run pytest
      run: |
        pipenv run pytest
        pipenv run pylint --rcfile=pylint.cfg $(git ls-files '*.py') -s true --fail-under=10
