name: pylint_pytest_ecr

on:
  pull_request:
    types: [opened, reopened, synchronize]
    
env:
  ECR_REGISTRY: public.ecr.aws/j2v6p8h8/webapp
  ECR_REPOSITORY: webapp
  IMAGE_TAG: latest

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Pull Docker image from ECR
        uses: docker/cli@v2
        with:
          command: pull
          args: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
      - name: Run Docker container from ECR image
        uses: docker/cli@v2
        with:
          command: run
          args: |
            -t
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
