name: aws-ecr-docker-image-pylint-pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Restore Docker build cache
      uses: actions/cache@v2
      with:
        path: /tmp/docker
        key: docker-${{ github.sha }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Pull the image from ECR, using the cached layers if available
    - name: Docker pull from Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_REGISTRY_URL }}
      run: |
        docker pull $ECR_REGISTRY

    # Run pylint and pytest on the pulled image
    - name: Run pylint and pytest
      env:
        ECR_REGISTRY: ${{ secrets.AWS_REGISTRY_URL }}
      run: |
        docker run $ECR_REGISTRY

    # Save Docker build cache for future runs
    - name: Save Docker build cache
      uses: actions/cache@v2
      with:
        path: /tmp/docker
        key: docker-${{ github.sha }}
        restore-keys: |
          docker-
