name: pylint_pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    inputs:
      secret_input:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    container:
      image: ${{ inputs.secret_input.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.secret_input.AWS_REGION }}.amazonaws.com/webapp:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.secret_input.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret_input.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ inputs.secret_input.AWS_REGION }}
      
    steps:
      - name: Pull Docker Image
        run: |
          aws ecr get-login-password --region ${{ inputs.secret_input.AWS_REGION }} | docker login --username AWS --password-stdin ${{ inputs.secret_input.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.secret_input.AWS_REGION }}.amazonaws.com
          docker pull ${{ inputs.secret_input.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.secret_input.AWS_REGION }}.amazonaws.com/webapp:latest
      - name: Run Docker Pylint and Pytest
        run: |
          docker run --rm -v $(pwd):/app ${{ inputs.secret_input.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.secret_input.AWS_REGION }}.amazonaws.com/webapp:latest
