name: pylint_pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGISTRY_URL: ${{ secrets.AWS_REGISTRY_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 
    steps:
      - name: Download AWS CLC
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Login to Amazon ECR
        run: |
           aws ecr get-login-password --region ${AWS_REGION} --registry-ids ${AWS_ACCOUNT_ID} | docker login --username AWS --password-stdin ${AWS_REGISTRY_URL}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_REGISTRY_URL: ${{ secrets.AWS_REGISTRY_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      - name: Pull Docker Image
        run: |
          docker pull ${AWS_REGISTRY_URL}/webapp:latest
      - name: Run Docker Pylint and Pytest
        run: |
          docker run --rm -v $(pwd):/app ${AWS_REGISTRY_URL}/webapp:latest
