name: Pylint

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  THRESHOLD: "5.5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Install packages with pipenv
        run: |
          pipenv install
      - name: Analysing the code with pylint
        run: |
          echo "threshold = 5.5" > pylint.cfg
          pipenv run pylint --rcfile=pylint.cfg $(git ls-files '*.py') -s true --fail-under=9
