name: pylint_pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          REGISTRY: ${{ secrets.AWS_REGISTRY_URL }}
          REPOSITORY: webapp
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Pull Docker Image
        run: |
          docker pull ${AWS_REGISTRY_URL}/webapp:latest
      - name: Run Docker Pylint and Pytest
        run: |
          docker run --rm -v $(pwd):/app ${AWS_REGISTRY_URL}/webapp:latest
